### ISSUE TITLE
Advanced Markdown Editor does not remember SideBySide setting

### ISSUE THREAD

**Issue by luckman212** [standardnotes/desktop#114]
SN (Mac) desktop version [2.0.41](https://github.com/standardnotes/desktop/releases/tag/v2.0.41)

Since updating from 2.0.3(?) I think, the Advanced Markdown Editor no longer remembers the toggle state of the side by side (preview) pane. I have to open it manually every time. Seems to be a new issue.

I've granted the new permissions & tried the _"Clear Cache and Reload"_ menu option which had no effect.

**Comment by mobitar** [comment]
Hmm that's strange, because there was nothing explicitly remembering that state before. Do you recall in what circumstances it would remember that state? Was it when you switched between notes, or even when you closed the app and re-opened it? I don't think it would have remembered that state between app sessions.

**Comment by luckman212** [comment]
I can't be sure now, but I do remember the editor preserving that state in between app launches. However, if you're saying there's nothing in the code to effect such a thing then I can't argue with that.

Consider it a feature request then!

**Comment by mobitar** [comment]
Ok, will do :) Definitely wasn't anything holding on to that state before, so it must have just been a coincidence.

**Comment by mobitar** [comment]
Still on the radar, but doesn't necessarily belong in this repo.
