### ISSUE TITLE
Feature Request: Ability to subscribe to other people's listed blogs

### ISSUE THREAD

**Issue by wireddude** [standardnotes/desktop#118]
would be nice if other users of SN could "subscribe" to their favorite listed blogs, and have them show up in the their own desktop or mobile app.

**Comment by mobitar** [comment]
Hmm..that's interesting. I think that would work in the form of a Component. I have plans to make Components that can act as full-screen experiences. In which case, you could browse different portals. Did you imagine it some other way?

**Comment by wireddude** [comment]
No, any way you imagine it is fine. Just not having to remember URLs of authors and go to a web browser is fine for now.

**Comment by mobitar** [comment]
Well you know of subscribing by email right? You can do that now. But I
assume you’re referring to like a sort of feed, right?

On Nov 27, 2017, at 1:14 PM, Wired Dude <notifications@github.com> wrote:

No, any way you imagine it is fine. Just not having to remember URLs of
authors and go to a web browser is fine for now.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/standardnotes/desktop/issues/118#issuecomment-347293439>,
or mute the thread
