### ISSUE TITLE
Note title and tags disappear as soon anything is typed in Simple Markdown Editor

### ISSUE THREAD

**Issue by rsau** [standardnotes/desktop#124]
After adding title and tag, as soon as I type anything in Simple Markdown Editor, both title and tag disappear. 

steps
1. add title[TAB]
2. add existing or new tag[ENTER]
3. type in note editor

Title and tag just vanish. 

I have tested with multiple notes by adding existing or new tags. I have cleared cache and reloaded as well as restarted appimage.

**Comment by mobitar** [comment]
That's..really strange. I can't replicate it. I tested your steps but don't see this. Can you please record a video of this. That would be very helpful.

**Comment by rsau** [comment]
I have sent you a video at me@bitar.io .

**Comment by mobitar** [comment]
Thanks got it!

**Comment by brian-hay** [comment]
Similar issue here using Mac 2.3.12. If I tab out of note title, when I start typing in Simple Markdown Editor the title reverts to default. Tags unaffected for me. If I press enter rather than tab in title then it stays when I begin typing in editor.

**Comment by mobitar** [comment]
I can't replicate this. Here's what I did:

1. Create a new note.
2. Set the editor for the note as Simple Markdown Editor.
3. Type "Foobar" in note title.
4. Tab twice to go into editor, which is in "Edit" mode"
5. Type anything in the body.

At this point, title and body remain as expected, and do not revert. 

Are you doing anything differently? I've also tried with setting SME as default editor instead of step 2. Same result though.
