### ISSUE TITLE
IndexedDB log files do not get deleted after encryption state change

### ISSUE THREAD

**Issue by maqp** [standardnotes/desktop#131]
I wanted to see whether the notes are properly encrypted so I did some tests
and found issues. Steps to reproduce on Ubuntu 17.10:

### Encryption of unencrypted database fails

1. After installing Standard Notes, remove `~/.config/Standard\ Notes/` and `~/Standard\ Notes\ Backups/` if they exist.
2. Open Standard Notes
3. Add **MySecret** as a note
4. `$ cd ~/.config/Standard\ Notes/IndexedDB/file__0.indexeddb.leveldb`
5. `$ cat 000003.log`
    outputs bunch of stuff, including "weN to e"1txetc**MySecret**"
6. Enable local encryption
    Account -> Add Passcode -> Enter and confirm passwords -> OK
7. Close Standard Notes (This is the point where data at rest must be encrypted)
8. `$ cat 000003.log`
    outputs encrypted database, including string "e"1txetc**MySecret**"

Since **MySecret** is still visible, it looks like client-side encryption fails.

---

### Re-encryption of unencrypted database fails

Steps to reproduce on Ubuntu 17.10:

1. After installing Standard Notes, remove `~/.config/Standard\ Notes/` and `~/Standard\ Notes\ Backups/` if they exist.
2. Open Standard Notes
3. Enable local encryption
    Account -> Add Passcode -> Enter and confirm passwords -> OK
4. Add **MySecret** as a note
5. `$ cd ~/.config/Standard\ Notes/IndexedDB/file__0.indexeddb.leveldb`
6. `$ cat 000003.log`
    outputs encrypted notes. Everything is working as it should.
7. Disable local encryption
    Account -> Remove Passcode -> OK
8. `$ cat 000003.log`
    Shows unencrypted notes, just like it should: "weN to e"1txetc**MySecret**"
9. Re-enable encryption
    Account -> Add Passcode -> Enter and confirm passwords -> OK
10. Standard Notes Reports "1/1 notes and tags encrypted"
11. Close Standard Notes (This is the point where data at rest must be encrypted)
12. `$ cat 000003.log`
    Shows unencrypted notes that should be encrypted: "weN to e"1txetc**MySecret**"

Both happen even when Data Archives are set to "Encrypted".

**Comment by mobitar** [comment]
Good catch. It's worthy to note that this only happens if you originally created data during an unencrypted state, then migrated to an encrypted state (via account or local passcode). The solution should have been as simple as deleting the *.log files by indexeddb, however, for some strange reason, deleting those .log files corrupts IndexedDB/LevelDB's ability to function properly.

So instead the solution I'm employing is to completely wipe out the database (which automatically wipes out the logs) whenever encryption is enabled, then to rewrite all items.

See https://github.com/standardnotes/desktop/commit/d79422b0b832349f834d60a91094696eba7d7e50. I'll post 2.0.43-beta1 shortly so you can verify the fix.

**Comment by mobitar** [comment]
2.0.43-beta1 available here: https://github.com/standardnotes/desktop/releases/tag/v2.0.43-beta1
