### ISSUE TITLE
Offline work - issue with duplicate notes and tags.

### ISSUE THREAD

**Issue by harrisondesbrosses** [standardnotes/desktop#139]
Hello!

I just thought I'd share this issue I had with SN over the weekend. I had finished importing a large amount (400 and some odd) of notes converted from Evernote & wanted to get busy tagging all of them over the duration of a long flight. Prior to the flight I had done some work while connected to WiFi -creating "folder" and subfolder structures using the folders extension which I do understand is simply using tags.

Somehow by doing offline work on the plane, I had created both duplicate notes, tags (folders and subfolders) and had a huge mess to sort out when I landed. I've gone ahead and manually organized the notes again. I had a sneaking suspicion that doing tag work while offline would have done something odd, so I will certainly avoid that kind of offline work in the future.

I'm sad to say I didn't take any screengrabs of the issue or anything, but I'm curious if anyone could explain what could have happened + how to avoid a similiar situation in the future?

**Comment by mobitar** [comment]
Duplicates occur in the case of sync conflicts, which is very simply the occurrence where you are trying to send a note to the server, and the server is trying to send you that same note at the same time. These kinds of conflicts are typically handled by the server, but because data is encrypted, the server cannot do anything meaningful with it. So the client app itself is tasked with the responsibility of deciding which of the two copies it should keep. Sync conflicts don't usually occur if you use the app monogamously and with a healthy connection, but are guaranteed to occur when you zag between online and offline states.

Usually it's not so noticeable because you aren't typically always doing large operations. But when you do these sorts of batch management tasks, and you do them with a wavering connection, you're going to see some duplication take place.

There are two things we plan to do to improve this:
1. Make item comparison a little smarter and more capable of resolving conflicts on its own without resorting to duplication.
2. Introduce a "Batch Manager" extension that allows you to manage your data in bulk, which has already been a very popular request.

If you're using the Desktop app and you ever screw up too bad, you can always look at the automatic backups it makes, and you should see some within the last few minutes or hours that you can restore to.

**Comment by harrisondesbrosses** [comment]
Hello again- 

Sadly I've experienced the same sync conflict again from an unforeseen factor - my mobile device! (iOS). Upon entering Standard Notes on my mobile device, the 136 notes I had manually deleted / sorted out on my desktop were pushed back up onto the server and are obviously now reflected in my desktop app.

What do you best reccommend for sorting this? I'll surely avoid creating such conflicts in the future, I'm sure about that... but I'm curious about what to do now. I'll re-sort the 136 problem notes by hand if necessary, but I've got a clean backup from after I finished sorting the duplicates out last night... and would prefer to do a clean restore.

Is there any way you can wipe all the notes from my account on your end so I can re-import from a backup? Seems like that would be best given that batch features are still being made.

**Comment by harrisondesbrosses** [comment]
Bit of an update: I manually sorted these one last time because I was in a bit of a time crunch. However, advice on a future situation that would require a clean wipe on the user / server end would be greatly appreciated.

**Comment by mobitar** [comment]
For now you can wipe all data using Account -> Advanced -> Data Dashboard -> Advanced -> Destroy all data.

However this option will soon be removed in favor of working towards a Batch Manager extension.

You can also delete your account entirely if you want to start over, although that may be too extreme. https://standardnotes.org/reset

**Comment by harrisondesbrosses** [comment]
Great, thank you!

I'm happy to close this if you are.

**Comment by mobitar** [comment]
Yup, sounds good!
