### ISSUE TITLE
Question regarding tags when clicking "+" button to create a note within a prexisting tag.

### ISSUE THREAD

**Issue by harrisondesbrosses** [standardnotes/desktop#143]
Hello-
I'm not exactly sure if this is an issue, or my own ineptitude... so I do apologize in advance for anyone having to clue me in here...

I'm currently using the Folders extension with Autocomplete tags, and obviously often use the former to filter out notes.

Now, when I attempt to create a new note while a subfolder tag is selected by using the "+" menu button, the new note is created with only the subfolder tag attached, but not the parent folder tag. Now, I find that odd because if I create a new note without any tag / folder selected and then use Autocomplete tags to select a subfolder, both the parent folder and subfolder tags are applied... which is what I'd ideally want to have happen when I create a new note with the "+" button.

Both parent and subfolder tags are also applied when I'm retroactively applying tags to notes I haven't organized yet by using Autocomplete tags and choosing the subfolder tag I want.

I'm happy to record a screengrab if necessary.

**Comment by mobitar** [comment]
Yeah, the folders extension needs some love. Was initially released as a proof of concept very early on, and I haven't had the chance to give it the love it needs. I'm contemplating taking it down altogether until I can spend more time on it. In any case, if you want to collect issues on the Folders component in particular so that I can work on them when I revisit it, you can do so here: https://github.com/sn-extensions/folders-component

Sorry this isn't the most helpful response!

**Comment by harrisondesbrosses** [comment]
Thanks for getting back - do you mind if I copy this issue over there then? A bit annoying I know, but as I'm sure you know GitHub doesn't let you move issues between repositories.

**Comment by mobitar** [comment]
Yup let’s do that

On Jan 26, 2018, at 1:34 PM, harrisondesbrosses <notifications@github.com>
wrote:

Thanks for getting back - do you mind if I copy this issue over there then?
A bit annoying I know, but as I'm sure you know GitHub doesn't let you move
issues between repositories.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/standardnotes/desktop/issues/143#issuecomment-360882775>,
or mute the thread

**Comment by harrisondesbrosses** [comment]
Done. Lastly - while we're here - can you confirm that having each note be assigned a parent / sub tag would be the correct use?

**Comment by mobitar** [comment]
Yes it should recursively ascend up the chain to add all parent tags.

On Jan 26, 2018, at 1:37 PM, harrisondesbrosses <notifications@github.com>
wrote:

Done. Lastly - while we're here - can you confirm that having each note be
assigned a parent / sub tag would be the correct use?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/standardnotes/desktop/issues/143#issuecomment-360883629>,
or mute the thread

**Comment by harrisondesbrosses** [comment]
Great! Last word on this until you work on folders, but just know that now that I know I could easily apply these tags and get a slightly more rugged 'folder' view without this extension... I'm cool continuing without it. I could see how novice converts from Evernote, or people a bit too fixated on clean looking design (me, a few days ago.. still a novice) would need this.
