### ISSUE TITLE
Extensions Troubleshooting on 2.1

### ISSUE THREAD

**Issue by nickAtWybar** [standardnotes/desktop#153]
Hi Mo, I've been playing around with the new extension manager, and I seem to have broken a few things. The plain text still works, but any extensions around it seem to be fairly broken:

- if I switch to advanced markdown editor, it shows blank for the note
- plus editor shows blank note
- action bar is blank / does not show up
- titanium/other themes don't change the interface colors

Tried fixes:
- A complete uninstall / reinstall hasn't fixed it either.
- install / uninstall of extensions from the new extensions manager
- many restarts / refreshes of the application
- uninstall / reinstall of the 'extensions' component. but perhaps this is what messed it up?

To note: all functionality except Action Bar still works on other computers, seems to be local to the one computer.

Thanks for all your work on the new update.

**Comment by mobitar** [comment]
Hey @nickAtWybar, what OS is this computer running? Are you using the desktop app or a web browser? Which browser if so?

If you could attach some screenshots, or screen recordings, would be helpful as well. The more details the better.

**Comment by nickAtWybar** [comment]
hi mo. This instance is running the desktop version on a laptop running Windows 7 Enterprise Service Pack 1, Standard Notes version 2.1.0. Other fix not mentioned above of course was several plain computer restarts.

The below screenshots are a test note I generated. One is in plain editor, the other in advanced markdown. The 'titanium' extension is activated (note without it being titanium), and you can't see it at the bottom but the action bar is also blank.

![plain](https://user-images.githubusercontent.com/6332337/36427015-2a81ac08-1609-11e8-8a62-025886075acd.JPG)

![same note but adv markdown editor](https://user-images.githubusercontent.com/6332337/36427025-31688b0e-1609-11e8-852d-a32d6a11bdca.JPG)

**Comment by mobitar** [comment]
Can you open the developer console and see if there's any error output? Use Ctrl+Shift+I (or Cmd+Opt+I on Mac) to open DevTools. Please paste in any output you see.

Also, what about if you try using the web app at https://app.standardnotes.org. Does this issue occur there too?

**Comment by nickAtWybar** [comment]
mo, it works on the web app and all my other devices (windows 10, iOS).

![image](https://user-images.githubusercontent.com/6332337/36453862-eaa66ee0-1656-11e8-8da3-f39d1f21d635.png)

![image](https://user-images.githubusercontent.com/6332337/36453874-f9b3cdb0-1656-11e8-999d-71bfc2a59c02.png)

looks like there are definitely some errors on the dev tools output window.

**Comment by mobitar** [comment]
Can you open the location specified in the red errors and tell me what you
find in there? Is there an Extensions folder? What does it contain?

On Feb 20, 2018, at 4:59 PM, nickAtWybar <notifications@github.com> wrote:

mo, it works on the web app and all my other devices (windows 10, iOS).

[image: image]
<https://user-images.githubusercontent.com/6332337/36453862-eaa66ee0-1656-11e8-8da3-f39d1f21d635.png>

[image: image]
<https://user-images.githubusercontent.com/6332337/36453874-f9b3cdb0-1656-11e8-999d-71bfc2a59c02.png>

looks like there are definitely some errors on the dev tools output window.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/standardnotes/desktop/issues/153#issuecomment-367151183>,
or mute the thread

**Comment by nickAtWybar** [comment]
hi mo, the extensions folder contains exactly one folder ('downloads'):
![image](https://user-images.githubusercontent.com/6332337/36454289-7e2b96ee-1658-11e8-980c-e253ec31a5f9.png)
note: does not contain ANY files in 'extensions'

the downloads folder contains:
![image](https://user-images.githubusercontent.com/6332337/36454310-93aaf47e-1658-11e8-80f1-77fea3a69838.png)

**Comment by mobitar** [comment]
Looks like the downloads are not unzipping. Can you try uninstalling an
extension and reinstalling and observe the log output for any unzipping
errors?

On Feb 20, 2018, at 5:10 PM, nickAtWybar <notifications@github.com> wrote:

hi mo, the extensions folder contains exactly one folder ('downloads'):
[image: image]
<https://user-images.githubusercontent.com/6332337/36454289-7e2b96ee-1658-11e8-980c-e253ec31a5f9.png>
note: does not contain ANY files in 'extensions'

the downloads folder contains:
[image: image]
<https://user-images.githubusercontent.com/6332337/36454310-93aaf47e-1658-11e8-80f1-77fea3a69838.png>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/standardnotes/desktop/issues/153#issuecomment-367153720>,
or mute the thread

**Comment by nickAtWybar** [comment]
mo, nothing seems to pop up in the console. Tried installing/uninstalling several editors and components.

**Comment by nickAtWybar** [comment]
ok randomly, it all appears to be working again as of this morning. The extensions appear to be unzipped now. Strange, as I didn't do anything. Maybe a few windows restarts was what it needed...?
Closing issue for now.

**Comment by mobitar** [comment]
Hmm strange indeed.
