### ISSUE TITLE
WikiWords (internal link) support

### ISSUE THREAD

**Issue by jalberto** [standardnotes/desktop#181]
Will be great to have WikiWord support to:

- internal links
- create new note on WikiWord click

**Comment by jalberto** [comment]
hi @mobitar, thanks for your answer,
why is out of scope? is to organize notes out of scope of a notes app?

linking notes is a way of:
- organization
- references
- knowledge mapping
- contextualization
- etc

**Comment by mobitar** [comment]
The only thing in scope for us is encryption and longevity. So it's not an attack necessarily on this feature, but any feature that is extra to what is already present. Some good reading:

https://standardnotes.org/longevity
https://listed.standardnotes.org/@sn/816/why-simplicity-is-the-only-way-forward

**Comment by jalberto** [comment]
I understand, but you already have features that add more complexity than
internal references, and it will nto affect longivity

**Comment by mobitar** [comment]
Internal features? I wouldn't think so..extensions, maybe. But with linking, it would be difficult to pull off with an extension, so I'm taking this request as a "core addition", which would be out of the question. But perhaps there's a way to do this as an extension..I just haven't given it any thought yet.

**Comment by jalberto** [comment]
thanks @mobitar I appreciate your time even if don't get your point yet.

The note app that I used more frequently, is Tomboy, I tried tons of note app, and I really like the idea behind Standard Notes. The best Tomboy features from me are:

- instant access, it is really quick to add or find note using Tomboy widget
- wikiwords, without it it's impossible to create a knowledge base

Implementing WikiWords in a way that doesn't affect main ideas behind Satandard notes is possible by adding a custom markdown formatting, typing in the note something like `[LinkToPageTitile]`, save it as plain text.
Then in render time, transform it into a internal reference to open the note by that title.

Out  of curiosity, How something like this can affect Standard Notes scope?

**Comment by mobitar** [comment]
Well we don't have any linking infrastructure right now. So that would need to be built on desktop/web. Then of course, users will see links on mobile and ask, why can I not click this link on mobile? So we'd need to build it for mobile. Mobile editors do not support clickable links unless they are in read-only mode, so without a lot of custom work, this would be a very complex undertaking.

Ultimately, our goal is not to be the best tool for every purpose, but the right tool for the right job. If Tomboy offers wikiwords, it's best to use that for that purpose. If you're looking for a general place to store encrypted notes that are synced and backed up, and accessible on every device, then that's what we're for :)
