### ISSUE TITLE
Feature request: custom tab indent size (tabulation width)

### ISSUE THREAD

**Issue by virtuallyvlad** [standardnotes/desktop#185]
On Windows at least, the default tab size in the plain editor seems to be 8 spaces.  It would be useful to set this to another amount, like 4.

**Comment by mobitar** [comment]
So the [code for this](https://github.com/standardnotes/web/blob/master/app/assets/javascripts/app/controllers/editor.js#L640) inserts a "tab" character if that feature is supported, and otherwise inserts 4 spaces.

Customization is delegated to extensions, so an option like this has a chance of making an appearance, but likely in an external editor.

**Comment by virtuallyvlad** [comment]
Ah, ok.  Any idea why the tab character defaults to an equivalent of 8?  Is this some default outside of SN?

**Comment by mobitar** [comment]
I'm not entirely sure, but I think that's just what the tab character is. It might be changeable though on a global level, haven't looked into it.

**Comment by virtuallyvlad** [comment]
Noticed that the default tab size had changed to 4 characters at some point, and is now 2 characters.  A custom tab size setting would be great, but it is nice to see the 8-char default gone.
