### ISSUE TITLE
[Feature request] search and replace

### ISSUE THREAD

**Issue by Random2965** [standardnotes/desktop#187]
I know that there is search function, but I could not find a way to replace stuff, e.g. search for "adn" and replace it with "and" inside a note. That would be really helpful.

**Comment by Random2965** [comment]
Cool, should I then open a new issue in one of the extension like, dunno, plus editor?

**Comment by mobitar** [comment]
No, it would have to be an editor we build ourselves :) Would be too difficult to modify an existing opensource one.

Or actually, we might just be able to find another opensource editor that supports search and replace natively. I think I've seen one before.

**Comment by mobitar** [comment]
That's the thing: it would be probably possible on Desktop, but not possible on web, due to external editors having to implement their own in-text search. Electron works by scanning the entire interface, including editors. Web browser don't have this same feature. Maybe we relent and offer this only on desktop, but that would be a dangerous precedent in compromising 1:1 feature parity between web and desktop.

**Comment by mobitar** [comment]
Search and replace is available with the Minimal Markdown Editor, for starters.

**Comment by TROMsite** [comment]
No new plans to bring this to other editors such as the Bold or Plus Editors. It is something I truly miss from Standard Notes.

**Comment by chaserene** [comment]
for those wondering, Markdown Minimist (previously called Minimal Markdown Editor) can do search and replace with these keyboard shortcuts:

Shift+Ctrl+F: replace
Shift+Ctrl+R: replace all

(source and more key shortcuts: https://codemirror.net/doc/manual.html#commands)
