### ISSUE TITLE
[Feature Request] - WebDAV as a cloudlink option.

### ISSUE THREAD

**Issue by zedgoat** [standardnotes/desktop#203]
Thinking if there's any demand for it outside of this +1 it would be useful to have WebDAV as a cloudlink option. There seems to be more privacy oriented / private service providers offering it (e.g., OwnCloud, NextCloud, Fastmail, pCloud) would be nice for standard notes.

Not the strongest driver (eg, encryption means it's perfectly safe to store in Dropbox or gCloud), but interested to see what the demand looks like. Thanks!

**Comment by mobitar** [comment]
Yeah, still trying to get an idea for how in demand this is. I know a small number of people would swear by it. I'm sure we'll get this one day. It's just a matter of prioritization.

**Comment by zedgoat** [comment]
Yeah, that's fine! The email backup covers the use case and most users are typically on Dropbox or gCloud, so it's a nice to have. Agree, interesting to see if it gets any traction over the next year or so.

**Comment by paolostivanin** [comment]
+1 for webdav :)

**Comment by Stele77** [comment]
Hi!
I think many people who are attracted to SN are also attracted to Nextcloud/Owncloud and comparable solutions. 
I for one am in the process of finding a secure and powerful Evernote alternative. SN is right at the top together with Inkdrop. Support for webdav and Nextcloud would be a huge plus in my book, even more so because some alternatives already support Nextcloud.

The demand is there for sure. And 99% of ppl would never bother to open an issue on Github, if they knew at all what Github is and how to use it...

What confused me is issue #248 there the OP says he is connecting FileSafe to his Nextcloud server. So is this already implemented? Is this issue closed?

Thank you in advance!

**Comment by zedgoat** [comment]
@Stele77, @mobitar mentioned on Slack that they are different back ends - so while Filesafe has webdav support, that doesn't directly translate to Cloudlink supporting it as well.

**Comment by mobitar** [comment]
@Stele77 are you wanting Nextcloud as a syncing store, or specifically for CloudLink and it's daily, one-way, backups? If syncing store, this is out of the question. But for CloudLink daily backups, this could be possible in the future.
