### ISSUE TITLE
Library that Removes Markdown Tags from List

### ISSUE THREAD

**Issue by infosisio** [standardnotes/desktop#220]
I begun using this and wanted to let you know about it:
https://github.com/stiang/remove-markdown

It works very nicely so far.

**Comment by mobitar** [comment]
The ideal solution to the syntax cleanup would be a linter extension or something of that sort. The idea is that while the editors we have now are limited to sort of Markdown and HTML, in the future, it can be arbitrary. So we don't want to hardcode things like HTML-cleanup, because it doesn't really solve the real problem. We need an extensible solution to this. Maybe editors themselves generate a "preview" field on each note, which is then displayed in the list.

**Comment by mobitar** [comment]
v3 takes care of this.
