### ISSUE TITLE
Input delay when typing on a Mac

### ISSUE THREAD

**Issue by GalacticSun** [standardnotes/desktop#243]
When trying to type and enter text in a note in Standard Notes, the text that is input is delayed.  It is frequently delayed by at least a half-second to over a full second, depending on how quickly I type.  If I then switch over to type in text in the Apple Notes app or Safari (to write this, for example) there is no delay. It is only with Standard Notes. I'm using the regular editor, btw.  I really want to use Standard Notes, but this typing delay is a deal-breaker.  Anything I can do to fix it?  Thanks.

**Comment by mobitar** [comment]
Very strange. I'm unable to reproduce this on my end, even when typing extremely fast. How is the memory pressure on your computer? Can you check with Activity Monitor to see if you are low on memory or CPU?

Also, can you try testing the web app at [app.standardnotes.org](app.standardnotes.org) and see if it works any better there?

**Comment by GalacticSun** [comment]
Not low on anything; 95%+ free both CPU & RAM.  Web interface is fine, no delays.

**Comment by mobitar** [comment]
I know it's silly, but any chance you can try restarting your computer and seeing if that makes a difference?

**Comment by christianhans** [comment]
As notes in my other issue #274 this is most likely caused by having spell check enabled with large notes.

**Comment by ArneTR** [comment]
Since this is the first result on Google I wanted to add a comment for another cause of the input lag.

I am running macOS with an external 4k monitor. In the display settings I have it set to "scaled". So effectively zooming-in.

This settings makes Standard Notes also lag when typing. Standard Notes does not have a high CPU load during typing. But the Window Manager does.

Possible is cause is that the underlying Electron does not work efficiently with the macOS Window Manager. 
The input lag goes away if I disconnect the external monitor or when I set the resolution to "unscaled".

**Comment by JaspalSuri** [comment]
Hi, I'm sorry to hear about that input lag that you're experiencing. May I ask how you're connected to the display? Are you using the Larger Text or More Space option, or something in-between? 

I wasn't able to reproduce this on macOS Mojave with a Mac mini connected to a TV via an HDMI cable. Using both "Scaled" and "Default for display" do not cause any issues on my end. 

I know that Chrome-based and Electron apps can cause the screen to flicker if a $60 adapter isn't used 🙄, but that's usually when a video is playing. It's possible that connection is causing other problems, but I haven't encountered any lag.   

Here are what my settings look like: 
![CleanShot 2020-05-12 at 21 27 38](https://user-images.githubusercontent.com/44656000/81771315-7f018500-9497-11ea-8f32-4ce74bc0f418.png)

**Comment by ArneTR** [comment]
I am using the "larger text" option.

Also I do have a 5 year old MacBook Pro. And on its own display I am also
using a scaled option. Maybe two scaled screens and electron are too much
for my old MacBook Pro :)

Using a no scaled mode is an easy fix, as I can scale in standard Notes
directly. For me the problem is solved. Just wanted to document it in the
issue, if anyone experiences the same issue.

For clarification: I use a display port connection. No HDMI. No adapters.

**Comment by JaspalSuri** [comment]
Thank you for providing all of those details and I'm glad that you have an alternative that works. :)

Like you've said, it could just be an issue with Electron (or macOS). 

I'll be sure to report this to the team! Thanks for the feedback!
