### ISSUE TITLE
A few FileSafe suggestions

### ISSUE THREAD

**Issue by brortao** [standardnotes/desktop#248]
I'm trying to use FileSafe with my Nextcloud instance.
Uploading files fails (the uploading part -- encryption works as expected) but with no descriptive error message.

I've tried a few different WebDAV configurations -- using `mynextcloud.com/remote.php/dav/files/USERNAME` as the server, or just `mynextcloud.com`. I've tried using a Nextcloud per-app password and my main password. None of these have worked, and without a more descriptive error message it's hard to continue!

A few suggestions:
* more detailed instructions for using Nextcloud would be great
* check the configuration/credential validity when adding a new integration, not just when trying to upload a file
* add more descriptive error messages

**Comment by mobitar** [comment]
Hey @brortao, it's hard to be more descriptive with WebDAV since the errors we get are generic themselves. But I agree this could be helpful. As for Nextcloud, the URL you should use would be found in the bottom left of your Nextcloud dashboard. It is indeed very similar to "mynextcloud.com/remote.php/dav", however, from what I've seen, without the "files/USERNAME" part. Have you tried that?

**Comment by brortao** [comment]
Alright, I see!

Using that URL did it -- looks like Nextcloud changed the path from `/remote.php/dav` to `/remote.php/webdav` at some point in the past. Thanks for your help!

**Comment by mobitar** [comment]
Ok great, glad it worked!
