### ISSUE TITLE
Sometimes side panels cannot be hidden/shown with double click on resizers

### ISSUE THREAD

**Issue by justyn** [standardnotes/desktop#268]
I'm not sure why, but after working once, I can no longer hide or show the note list or tags side panels by double clicking on the resizers.

version: 2.3.13
os: Ubuntu 18.04

Any steps I should take to debug?

**Comment by mobitar** [comment]
I can't replicate this..

**Comment by bryvin** [comment]
I can confirm this is actually the case for both web and desktop on Ubuntu for me as well. I've never tested double clicking before.

My first guess is that since the resizers now create an overlaid element so that it knows when you let go of a drag (the iframe's were previously eating the mouse up events)... that when you click that second time it's clicking on the created element for the resizers which may be affecting the behavior. I'll take a look at this.

**Comment by mobitar** [comment]
Hmm..strange that it's an Ubuntu thing.

**Comment by bryvin** [comment]
Just have done some further testing.. and here is what I have found so far:

**On Desktop**
- Default Theme works just fine
- Future Theme works just fine
- Midnight Theme does **not** work as intended

**On Web**
- My first times trying it it didn't work as intended
- Switched to default theme and it worked
- Switching back to Midnight did allow it to actually work

I just updated to the newest Desktop production version through the menu at the top and it still does not work for my the Midnight theme.. but does work for Future and default.

@justyn Can you confirm if you have a theme on your account and which one?

**Comment by justyn** [comment]
@bryvin yes that is right, I'm using the Midnight theme and it doesn't work, but it does with Futura.

Switching back to Midnight from another theme, or deactivating and reactivating midnight, it still doesn't work.

**Comment by mobitar** [comment]
Ha, of course, I [change](https://github.com/sn-extensions/midnight-theme/commit/ecb48b58970824dbc1d8a2b638a985d0ba5d86d8) one tiny thing in the Midnight theme and it comes out the other end. I'll have to revert this change. @bryvin good catch on the Midnight theme.
