### ISSUE TITLE
Synchronization issues!

### ISSUE THREAD

**Issue by Raj2032** [standardnotes/desktop#291]
I keep having synchronization issues. If I were to add something to my notes using the Windows version, the Android version quite often won't get the new contents unless if I refresh and same vice versa.

I shouldn't have to worry about if the notes have been updated or not, it should automatically update all the notes.

**Comment by virtuallyvlad** [comment]
Looks like there may still be some server issues persisting.

On the web client, I had trouble just logging in and once logged in every other sync request was dropped.

![capture](https://user-images.githubusercontent.com/37453320/50705653-7e4a1a80-1029-11e9-9955-b16cfaffb134.PNG)

On the desktop client, I've had a couple of sync requests dropped but it's been mostly usable.  But the "All changes saved" has been glowing orange, on and off, for the past couple hours.  Not sure what that means, perhaps congestion/timeout related?

**Comment by Raj2032** [comment]
This has been happening for months though.

Sometimes I am forced to refresh in order to get all the notes and this
shouldn't happen, what should happen is that I should get all the notes
automatically.

**Comment by virtuallyvlad** [comment]
> This has been happening for months though. Sometimes I am forced to refresh in order to get all the notes and this shouldn't happen, what should happen is that I should get all the notes automatically.

Woops, disregard my original comment.  If it's been happening for months that may be a more unique problem.  SN should be syncing all of your notes automatically.  For example, if I create a note on my phone, that note appears in my desktop client in about 10-20 seconds (without hitting refresh).  Anything longer and I would assume internet connectivity is an issue - like if you are using the phone in an area with poor or congested cellular coverage.

**Comment by Raj2032** [comment]
I don't have poor connection issues, but thanks for letting me know, I will
try and wait for 10-20 seconds for it to automatically refresh and update
my notes.

**Comment by mobitar** [comment]
Changes are pulled in every 30s, or when you launch the app. It's not real time.

**Comment by Raj2032** [comment]
It would be better if it was in real time.

**Comment by bryvin** [comment]
I don't believe it's really feasible to offer real time sync and not really sure the benefit it would add. Standard Notes offers an account for 1 person (not a team), so it makes sense that 1 person would not need to have realtime notes on multiple devices at the same time. If you switch devices and need it immediately available on said device, you can refresh manually with the "Refresh" option. From my usage of the app(s) it typically isn't the full 30 second delay for when I make a change to when I see it on the other device. This is true only when you're at the right time in the sync cycle.

For example you're writing to a note on your phone and have your Desktop app open which just synced 20 seconds ago. Well now you're done on your mobile app and are going to complete work on the Desktop; technically it would sync within 10 seconds as it has already been 20 seconds since the last sync; and again, if you need it that much sooner you can just manually refresh with 1 simple click.

Can you explain the use case for a realtime sync?

**Comment by mobitar** [comment]
Real time sync would require a whole new technology stack of websockets. Adds a lot of complexity. However, you should hardly notice the 30s delay because:

1. The desktop app immediately syncs when it gains focus or launches
2. The web app immediately syncs when the tab gains focus
3. The mobile app immediately syncs when it resumes from background or launches

Of course, they all sync any time you make a change to any note.
