### ISSUE TITLE
Empty tag always "create" ready to use (but not persisted) note

### ISSUE THREAD

**Issue by x80486** [standardnotes/desktop#297]
If there is an empty tag, when its content is viewed there is always a default empty note "created". I understand the note is not actually created and/or persisted – or at least that's my assumption after viewing `All` of them.

I think that default note behavior is quite annoying. I'm not sure if that's on purpose or not, hence this issue.

**Comment by mobitar** [comment]
It's more of a convenience feature, so that you waste no time creating new notes. It may be annoying to some, but largely, I think it's a good timesaver in a large percent of cases: you're viewing a tag with no notes. Why? You already knew it had no notes. So why not save you a step and create a placeholder? This behavior is also inherited from initial app launch behavior for new users. The "All notes" section doesn't initially have a note, so we start one. Otherwise, new users would be looking around for the + button. It's just an "always ready" sort of interface decision.

**Comment by x80486** [comment]
OK, I didn't know the reason :sunglasses:

I know I'm more the type of user: I'll create all that stuff on my own, just don't do anything for me – or in my behalf, but I understand what others might prefer also.
