### ISSUE TITLE
Windows session expire dialog never closes

### ISSUE THREAD

**Issue by YoLieR** [standardnotes/desktop#318]
Hey,

I recently had to create a new Standardnotes account and delete my old one.
In the windows client I now can't sign into my new account because the "Session Expired" Dialog always appears on startup and reappears again immediately after I closed it. Because it's always in focus I can't click on the Account button to login with my new credentials.
I even reinstalled the client but the problem remains.

![2019-02-13 07_42_13-notes](https://user-images.githubusercontent.com/7194382/52692301-d26ae780-2f63-11e9-95cc-90df9129cdff.png)

Any suggestions? Is this behavior reproducible?
Thanks

**Comment by mobitar** [comment]
Sorry about that, this issue will be fixed in the next release. In the mean time, you can delete your application data to get back in. Click the top level Help button (if you can), then click Open Data Directory. Delete everything in there, and relaunch the app. If you can't access that menu item, the data directory is  `%USERPROFILE%\AppData\Roaming\Standard Notes`.

**Comment by YoLieR** [comment]
Thanks that worked 👍

**Comment by mobitar** [comment]
The infinite loop of alerts issue should be fixed in 3.0.5.
