### ISSUE TITLE
Selection is incorrect after undo (Markdown editor)

### ISSUE THREAD

**Issue by jackbaty** [standardnotes/desktop#324]
Using version 3.0.6 on macOS Mojave latest...

1.  Switch to the Advanced Markdown Editor in any note.
2. Select a word
3. Add bold formatting either using the toolbar button or by pressing `Command-b`
4. Undo the formatting by pressing `Command-z`

The selection will be two characters right of where it should be.

After `Command-b`...

![2019-03-13-note1](https://user-images.githubusercontent.com/970/54314344-ccdbde00-45b1-11e9-850e-b1d0dd8277a8.png)

After `Command-z`...

![2019-03-13-note2](https://user-images.githubusercontent.com/970/54314351-d1a09200-45b1-11e9-912b-f949aeb5272f.png)

**Comment by mobitar** [comment]
Hey @jackbaty, interesting find. The Advanced MD editor is not built by us, but is an open source component, so it's unlikely we'll fix this ourselves. The most active fork is here: https://github.com/Ionaru/easy-markdown-editor

I'm closing this issue here, but if you want to re-open it in the dedicated repo here, feel free to do so: https://github.com/sn-extensions/advanced-markdown-editor

**Comment by jackbaty** [comment]
Ah, I didn't realize it was a third party component. I'll check with them, thanks!
