### ISSUE TITLE
Autocomplete for tags when pressing tab bar on desktop app

### ISSUE THREAD

**Issue by CR0CKER** [standardnotes/desktop#44]
Adding a tag to a note is cumbersome because the full tag has to be typed out, otherwise the app immediately created a new tag. It should be possible to use the Tab-key to autocomplete an existing tag, and new tags should trigger a confirmation window to make sure not every type leads to a new tag.

**Comment by mobitar** [comment]
Probably not going to happen anytime soon.

**Comment by CR0CKER** [comment]
Why don't you keep a list of improvement ideas here on Github with a label like "enhancements" (which you've added to this suggestion) so once there is capacity for this it gets done? If you close pretty much every issue and suggestion people are raising, there's no list for other contributors to see what ideas and suggestions have already been made in the past. Just because something is probably not going to happen soon doesn't mean there shouldn't be a record on Github for this suggestion. 

I think as long as tags work the way they do now, they are a huge hassle to add and remove. Since this is one of the very few features StandardNotes has right now, and a pretty crucial one as well, it makes sense to make it work as well as possible. I don't think I will start using StandardNotes as my main note-taking app as long as I literally have to type out the full tag every single time I am tagging a note.

Please consider how this project can build active support from more contributors if "it won't happen anytime soon" is enough of a reason to shoot down a suggestion that is, in my opinion, almost a no-brainer.

**Comment by mobitar** [comment]
>  so once there is capacity for this it gets done?

This is not that kind of project. Sorry to be brusque. But I'm managing 15 different repos and a bunch of tweets, emails, bugs, improvements — and I'm just one person.

Please give https://standardnotes.org/ a read (changed from the last time you read it), and I think you will better understand where I'm coming from.

**Comment by mobitar** [comment]
Relevant part: 

<img width="703" alt="screen shot 2017-03-01 at 3 19 01 pm" src="https://cloud.githubusercontent.com/assets/3277844/23481799/6b5fa91c-fe92-11e6-8a32-323cd0272b36.png">

**Comment by masvil** [comment]
I agree with @CR0CKER. The actual tags management system on iOS app is far away better than the Windows app because you can assign existing tags to a note by selecting them from a list without having to entirely type them.

@mobitar I see your points and thank you for your effort. Anyway, please consider that a mass adoption needs convenience. If some users are moving from Evernote to Simplenote it's because the latter is tiny and simple. It only uses tags to organize notes without bloating stuff like categories etc. That's because its tags management is VERY user-friendly.

So I hope to see this issue open again too because I love everything of Standard Notes and I want to be able to spread the world (aside crypto-nerds) :)

**Comment by mobitar** [comment]
Don't worry, I'm still thinking about this. I'm open to convenience, but it has to come in the right way. In this case, I mean extensions. In the near future, users will be able to choose an extension for tag management, note list display, tags tree view, etc. But we have to be smart about it, and not just rashly develop features because we can :) That's a slippery slope.
