### ISSUE TITLE
Theme Selector Doesn't Show All Themes

### ISSUE THREAD

**Issue by kylejbrk** [standardnotes/desktop#537]
The theme selector on the bottom right only shows half of the themes I have installed:
![image](https://user-images.githubusercontent.com/35229089/80769381-03a8e680-8b1b-11ea-8cba-6f44b95c0302.png)

Is there any reason why the other three don't show up? The ones that do display are Dracula, Focus, and Futura.

**Comment by JaspalSuri** [comment]
Hi Kyle,

> Is there any reason why the other three don't show up? 

That's because each theme that's sitting there was either a newly installed theme or used is frequently by the user. This makes it quicker to access by the user. One downside is that you might forget to use the other themes. Do you frequently use all of the themes? I would suggest installing six more themes If you'd like those six to be eventually be available. You can grab some more themes made by the community [from here](https://github.com/jonhadfield/awesome-standard-notes). 

I currently don't know how long it takes for a theme to replace another theme that's quickly accessible. @baptiste-grob would know more about this.

**Comment by mobitar** [comment]
For custom themes, you need to do a little extra to get the dock icon to show up: https://github.com/standardnotes/docs/issues/5

**Comment by kylejbrk** [comment]
@mobitar thank you just noticed this in the JSON. I guess the official midnight theme doesnt support this?

**Comment by mobitar** [comment]
All of our official themes do support the dock icon. If you don't see it, try uninstalling then reinstalling the theme.
