### ISSUE TITLE
Ctrl-N should create a new note

### ISSUE THREAD

**Issue by dergigi** [standardnotes/desktop#591]
There should also be a menu item for it imho.

If there already is a shortcut and a menu item I can't find it.

**Comment by JaspalSuri** [comment]
Currently keyboard many common keyboard shortcuts (outside of the editors) aren't supported, but they are on the dev team's roadmap for future releases of the app.

**Comment by JaspalSuri** [comment]
I'm going to close this issue since it's similar to #593. Please let us know if you have any questions!

**Comment by notflip** [comment]
@JaspalSuri Where can I see the roadmap?

**Comment by JaspalSuri** [comment]
Hi @notflip,

We currently do not have a [publicly available roadmap](https://blog.standardnotes.org/being-a-quiet-software-company/). That said, the dev team is currently working making the refactored apps more stable for version 3.5 and will work towards redesigning them for version 4.0. Work on resolving issues pertaining to keyboard shortcuts is scheduled around the 4.0 update (i.e. sometime before or after) _for now_. Since it is a technical challenge, I can't estimate how much time it will take to fix, but it's definitely on our radar. 

You're still more than welcome to ask us any questions that you might have. 🙂
