### ISSUE TITLE
Error occurred while changing your backups directory

### ISSUE THREAD

**Issue by zxc23425** [standardnotes/desktop#595]
### Description:
No backups (2wks) after attempting to change default backup location.

### Purpose:
Change default backup directory from root, to user directory, so as to automatically be included in Deja Dup backups.

### Previously:
Backups worked. Manually copied backups to: Home/Documents/STANDARD NOTES BACKUP.

### Steps to reproduce the behavior:
1. Menu/Backups/Open backups location (/home/user/snap/standard-notes/10/Standard Notes Backups)(default)
2. Menu/Backups/Change backups location (/home/user/documents/STANDARD NOTES BACKUP)(does exist)
3. Menu/Backups/Change backups location (/home/user/documents/) error: adds oldest .txt file to path (documents directory chosen, not path to file which does not exist)
4. remove oldest .txt file; error: adds NEW oldest .txt file to path
5. remove all backups to temp directory ; rmdir error
6. attempt to revert to default backups directory; same errors

### Expected behavior:
Backups in changed directory.

### **Screenshots**
![Screenshot from 2020-08-19 09-19-23](https://user-images.githubusercontent.com/51143332/90585359-df266680-e1fe-11ea-90a4-e2df46492702.png)
![Screenshot from 2020-08-19 09-18-41](https://user-images.githubusercontent.com/51143332/90585366-e0f02a00-e1fe-11ea-9df5-746d66556512.png)
![Screenshot from 2020-08-19 08-49-18](https://user-images.githubusercontent.com/51143332/90585367-e188c080-e1fe-11ea-8a21-03bb60428ab1.png)
![Screenshot from 2020-08-19 08-29-11](https://user-images.githubusercontent.com/51143332/90585369-e2215700-e1fe-11ea-88f5-d39dd8c0df1a.png)
![Screenshot from 2020-08-19 08-21-58](https://user-images.githubusercontent.com/51143332/90585370-e2b9ed80-e1fe-11ea-8ba8-05e2837529f6.png)

### Desktop:
Linux ubuntu
Standard Notes 3.4.2

### **Additional context**
Awesome program. First problem I've had.

**Comment by zxc23425** [comment]
Sure, can you advise how I might backup manually? And how would I restore (to an AppImage installation without the backup problem) given the current problem? Copying/pasting files would take awhile at this point due to the number of files.

**Comment by JaspalSuri** [comment]
> And how would I restore (to an AppImage installation without the backup problem) given the current problem?

If you have an account with Standard Notes, then it should simply load all of your notes and wouldn't require you to restore a backup to your notes. Once you have the other version of the desktop app installed, it should allow you to change the location of the backups. 

If you don't have an account with Standard Notes, you would click on the `Account` button at the bottom left corner of the app and then click on the `Import Backup` button (currently only the encrypted backups are accepted, so it should be easy in this case). 

> Sure, can you advise how I might backup manually? Copying/pasting files would take awhile at this point due to the number of files.

Can you provide me with an estimate as to how many backup files there are? I wonder if the amount is relevant to the issue. 

I'm afraid that other than manually moving files to the new backup location, using something like [FreeFileSync](https://freefilesync.org/), using a cloud storage provider's desktop app that can backup certain folders from your computer, or using our [CloudLink](https://standardnotes.org/help/28/how-do-i-enable-daily-email-backups) extension to avoid the problem altogether, there isn't an easier way to back them up.

**Comment by zxc23425** [comment]
Thanks, these are great solutions!

**Comment by JaspalSuri** [comment]
You're welcome! Please let us know if you have any other questions!

**Comment by c0f** [comment]
I know this issue has been closed but I had the same problem with the Snap,  I also tried to change the location of the backup files.  I'd rather not switch to the appimage because I prefer the way Snaps automatically update.

I had two backup directories, neither of which were manually created by me:

"~/snap/standard-notes/**10**/Standard Notes Backups" and "~/snap/standard-notes/**11**/Standard Notes Backups"

Both directories contained the same 204 backup files and there were no backup files created since 28th July.  Automatic backups were enabled.  I use Standard Notes on an almost daily basis so I would expect a number of backup files to have been created since 28th July.

I tried to disable and then re-enable automatic backups but that did not restart the creation of automatic backups.

To fix the problem I:

1) Downloaded a manual backup from within the Standard Notes desktop snap app (just in case!)
2) Removed the standard-notes snap (snap remove standard-notes)
3) Removed the entire ~/snap/standard-notes directory
4) Reinstalled the snap and logged in (snap install standard-notes)

I now have only one backup directory (/home/bod/snap/standard-notes/11/Standard Notes Backups/) and automatic backups are being created.  

I'd like to move the backup location to another drive but I'm afraid that trying to change the backup location will break automatic backups.

Regards.

**Comment by JaspalSuri** [comment]
Hi, thanks for letting me know about this! It appears that the issue is with Snap versions of the app for some reason. I'm afraid that I currently can't reproduce the issue, but I'll be sure to pass this along for review. #597 

The good news is that the desktop app offers the ability to update seamlessly for all platforms (although there is a bug in which the option to update the app might not always appear).
