### ISSUE TITLE
Paste and Undo Problem

### ISSUE THREAD

**Issue by FrozenVertx** [standardnotes/desktop#756]
Hi,
I have StandardNotes Linux app in my Zorin OS and It have 2 problems
1.when I paste something in app then it paste it 2 or more times instead of just one
2. when I undo in Linux it sometimes Undo whole Note and make it blank or undo 5 to 6 steps back instead of one like Windows.

I don't know its my OS fault or SN so please check and fix issue.

**Comment by JaspalSuri** [comment]
Hi @FrozenVertx, I haven't been able to reproduce this issue (nor recall similar reports) in Ubuntu, so it's possible that the issue is exclusive to the Zorin OS Linux distro. 

If you're using the AppImage, can you try using the Snap and vice versa? Also, can you test the [web app](https://app.standardnotes.org) to see if the issue is reproducible there as well?

**Comment by FrozenVertx** [comment]
Hmm I tried Web app its works fine. I resetted My Zorin and now both works fine on AppImage, I think it's my Zorin's fault.

Thank's for suggestion

**Comment by JaspalSuri** [comment]
We're glad to hear that resetting the desktop app helped fix the issue; thank you for taking the time to do that! Have a great weekend!
