### ISSUE TITLE
Extensions stopped working after the new update. 

### ISSUE THREAD

**Issue by makarandh** [standardnotes/desktop#789]
After updating to version 3.9.3 of the desktop app for Linux, the extensions stopped working. It says my subscription expired and my extensions are in read only state. But my subscription hasn't expired. 

I tried following the steps here: [https://standardnotes.com/help/41/my-extensions-appear-as-expired-even-though-my-subscription-is-still-valid](https://standardnotes.com/help/41/my-extensions-appear-as-expired-even-though-my-subscription-is-still-valid) but to no avail. Also, that help page needs to be updated since the UI has changed in the last update. 

I even tried signing out and clearing local data and still I am facing the same problem.

**Comment by Saldef** [comment]
Having similar issue here, the difference is I am not even seeing the Extension option, it disappeared. I logged in to the web app and same issue remained.

**Comment by jbeldia** [comment]
Hi @makarandh, I'm afraid this is a known issue on some accounts after the updates on v3.9. We're currently investigating the issue, so can you send us an email at help@standardnotes.com, and let me know your account email as well?

> Having similar issue here, the difference is I am not even seeing the Extension option, it disappeared. I logged in to the web app and same issue remained.

Hi @Saldef, please do email us as well and let me know your account email. The Extension menu is no longer there, since we've implemented changes to the app, such that users with subscriptions no longer need to install extensions by themselves, They're simply made available to you on the apps. We'll be pushing updates to the help documentation to reflect this as well!

**Comment by Saldef** [comment]
@jbeldia I've emailed you already, and got the necessary help that solved my issue. 

it seemed I was using an earlier version, namely version 3.9.0, that had that bug, which I got from Snap, and in my case the issue only appears when I try using a custom editors, or any other unofficial extension as a matter of fact. Because the latest version (Version 3.9.3) wasn't available yet on the Snap Store, I installed it from the one in Github, and it solved my problem.

**Comment by xthursdayx** [comment]
I do not have a subscription, but I self-host all of the extensions I use in Standard Notes - some created by Standard Notes and some from the broader community. However, after the most recent update all of the editors created by Standard Notes (e.g. Simple Task Editor) no longer work and there is a banner at the top of the editor window that says
> You do not have an active subscription. 
> Simple Task Editor is in a read-only state.

I'm wondering how to fix this, or whether SN's open-source extensions will no longer be self-hostable. Thanks.

**Comment by tio-trom** [comment]
Same here. Self hosting and I see that message. Works well with my hosted standardnotes webapp, but not this standardnotes desktop app.

**Comment by moughxyz** [comment]
3rd party extensions do not require a subscription. However the way we detect if an extension is 3rd party or 1st party is by its identifier. So if the identifier is "org.standardnotes.bold-editor", regardless of where it's hosted, it will be treated as a first party extension and will enter into subscription validation logic.

You'll want to change the identifier for self-hosted extensions if they are our extensions and have the appropriate OS license.

Note that TokenVault [does not have a redistribution license](https://blog.standardnotes.com/why-tokenvault-is-going-public-source) so repackaging that and redistributing it to other users is not fair use.

**Comment by tio-trom** [comment]
I am grateful to you for making these tools open source, and sad at the same time when I see the artificial barriers that developers put, making it more difficult to self host these open source tools. Building walls online is far more time consuming and cumbersome than not creating any wall at all. Or am I wrong? I feel like this change is related to the "paid" subscriptions, and not an improvement to the software itself.

**Comment by moughxyz** [comment]
These aren't artificial barriers. We develop with our first party use case in mind because that's the 99.9% use case. Self-hosters don't pay with their dollar, but it's understood the compromise is that you pay with your time.

> I feel like this change is related to the "paid" subscriptions, and not an improvement to the software itself.

The former funds the development of the latter. There is no software without "paid" subscriptions. You'll have to thank all these paying subscribers for giving both you and us the ability to continue to building, improving, and hosting this software.

**Comment by tio-trom** [comment]
> These aren't artificial barriers. We develop with our first party use case in mind because that's the 99.9% use case.

Ok so the changes are to make it more reliable for you to make more money out of subscribers. Not to improve the software per-say. Not criticizing honestly, but trying to understand why those changes. I thought they are for security reasons or stuff like that. 

> Self-hosters don't pay with their dollar, but it's understood the compromise is that you pay with your time.

If you make your software open source then you probably understand that others will use it too. On top of this self-hosters are also testing the software, reporting or fixing bugs, and so forth. 

> There is no software without "paid" subscriptions. 

I disagree - https://www.directory.trade-free.org/category/software-hardware/ . We have directories of "trade-free" software. No pay, just use. Not with currency, data, or attention (ads).

> You'll have to thank all these paying subscribers for giving both you and us the ability to continue to building, improving, and hosting this software.

It is great that you get support. Thank you for this software. Maybe you should also try donations so it won't force you to spend time on making it more difficult for non-paying humans to use the software. May allow more improvements and will keep this software more community oriented. I would gladly donate a few bucks a month for this. But I won't pay for a subscription since that helps to keep this software only for the ones who can afford it. And that I do not accept. We should help all humans, not just those that have more money.

Sorry. Long comment.

**Comment by GRMrGecko** [comment]
Just a note about where I'm at wit this. I was going to give Standard Notes a try to see if it ends up being a replacement for how I organize my notes currently, which is just a directory of markdown files. I saw this was open source and available to self host, thinking if I were to self host I can get the extensions for free using https://github.com/iganeshk/standardnotes-extensions to get mark down support. But with this change, I am unable to do so.

I didn't see it being worth me sending my money until I tried it, you don't offer a free trial, so I was just going to try it by self hosting as I self host many things including Bitwarden. I ended up liking Bitwarden enough to get a subscription to support them, I would have probably done the same with Standard Notes if I ended up liking it. Now I have no way of knowing if I'd like it enough to give you money.

I self host because I don't believe in using something for my personal items unless I own the data, and have the ability to keep using the product if the company were to die or go the wrong route. You seem to be going the wrong route now, and I will be looking forward to find forks that remove this limitation.

I will keep an eye on this thread to see if you guys change your mind on this decision to allow me to try your product and see if I want to send you money.

**Comment by makarandh** [comment]
Closing it as it is fixed for me.

**Comment by deslee** [comment]
> These aren't artificial barriers. We develop with our first party use case in mind because that's the 99.9% use case. Self-hosters don't pay with their dollar, but it's understood the compromise is that you pay with your time.
> 
> > I feel like this change is related to the "paid" subscriptions, and not an improvement to the software itself.
> 
> The former funds the development of the latter. There is no software without "paid" subscriptions. You'll have to thank all these paying subscribers for giving both you and us the ability to continue to building, improving, and hosting this software.

I disagree with what I think you're saying. I think the differentiating features of Standard Notes that draws in a lot of its users are things like security, open sourced extensions, and self hosting. Pushing updates that break existing open source extensions and existing self hosted installations might not affect the bottom line immediately, but it definitely undermines some of the core values that make me want to support Standard Notes. I don't use Extended because I want to self host all my data, but I may also consider donating or sponsoring if I use it enough. Right now I have to use an older version of the Standard Notes app because my self-hosted extensions keep breaking - it happened in Nov 2021 and again in Feb 2022. I understand self-hosters are not your priority, and I can take the time to figure out why my installation broke when I have free time, but I would still appreciate some heads up or extra documentation on these breaking changes when they come up.

**Comment by moughxyz** [comment]
Here's a retrospective: https://blog.standardnotes.com/33124/roadmap-update-march-2022

Yes ideally we'd do much better at communicating breaking changes well in advance, but admittedly we don't have a good channel of communicating with our self-hosters. In most cases most self-hosters would probably only reliably find out by the breaking change itself.

An in-app communication/news mechanism would be the most ideal approach but we haven't built that out yet.

**Comment by deslee** [comment]
Thanks for responding! I admit I should have read the blog before commenting. It's reassuring to know that a guide to self-hosting is on the list of things to come.
