### ISSUE TITLE
Cyrillic filename encoding of decrypted plain text files (direct export from SN desktop)

### ISSUE THREAD

**Issue by sanchoio** [standardnotes/desktop#98]
If you use decrypt.html, filename encoding of decrypted plain text files which have non-ascii title is just fine and it is utf-8 as expected. Meanwhile the same export from SN app generates malformed and unreadable filenames. Expected behavior: one should always use **utf-8**. In summary, decrypt.html deals correctly with cyrillic encoding meanwhile SN App itself not.

**Comment by mobitar** [comment]
Can you share a sample note title/text with cyrillic characters so I can test it?

**Comment by sancho-one** [comment]
Yes, of course. Here it is:

[Текст в кириллице.zip](https://github.com/standardnotes/desktop/files/1369779/default.zip)

**Comment by mobitar** [comment]
I'm not able to replicate this issue. Can you describe exactly the steps I should do using this note?

**Comment by sancho-one** [comment]
Well, first convert this file to SN format, and then import it. Afterwards,
a) export encrypted backup and decrypt it with offline decrypt tool, find
Cyrillic file in plain text folder; b) export unencrypted plain text folder
directly from SN app, find pseudo-cyrillic filename; c) compare filenames
from a) and b): they are different. Filename encoding from step a) is Ok
and from b) is broken.

**Comment by sancho-one** [comment]
By SN App I mean SN Desktop App which produces broken Cyrillic filenames.

**Comment by mobitar** [comment]
Hmm I still can't reproduce this. Here's what I did:

1. Download your file from above.
2. Use the [Tools](https://dashboard.standardnotes.org/tools) to convert the Markdown file into an import file.
3. Import the file using the SN app.
4. Import successful.
5. Download "Decrypted" Data Archive using SN app.
6. Open zip file.
7. See file with name `Текст в кириллице-0c902a1e-6e45-464d-9c44-c22625d4af36.text` and contents: 
```
# Текст в кириллице

Текст в кириллице, текст в кириллице, текст в кириллице.

Просто какой-то текст в кириллице.
```

Are these the right steps?

**Comment by sancho-one** [comment]
Yes, that's steps are absolutely correct. And the resulting filename in step 7. is either correct. Do you see the correct name inside zip file before extracting archive? As for me, I see this "wrong' filename encoding **inside** zip file created with SN Desktop (BTW it affects not only Cyrillic, but Spanish non-ASCII chars such as stress signs either). However **once** zip file **extracted,** file names become **correct**. To eliminate the probability that it's the problem with my ZIP program, I've just compressed again the extracted folder, but with my ZIP program and non-ascii names are OK. I suppose that the problem is with settings for zip command in SN App... But again this issue is **not critical** and it's rather aesthetic as extracted filenames are ok. The only problem, it may somehow frighten potencial customer who uses non-ascii alphabet (and as you see, it affects not only Cyrillic, but Spanish, French, German, etc. with there special symbols in alphabet).

![screenshot from 2017-10-10 10-20-25](https://user-images.githubusercontent.com/32115115/31395476-6987d380-ada6-11e7-9ef0-1ca06356fbea.png)

**Comment by mobitar** [comment]
Ah I see. In my case on a Mac, there's no such concept of "inside a zip file". You can only extract it to view contents. That's why I wasn't able to see same results. I'll investigate when I get the chance to see what's causing this for Linux.
